# Generated by Django 5.0.9 on 2024-09-18 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "membership_id",
                    models.CharField(default="KMC", max_length=50, unique=True),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="male",
                        max_length=50,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=13, null=True)),
                ("email", models.EmailField(blank=True, max_length=150, null=True)),
                ("designation", models.CharField(default="member", max_length=100)),
                (
                    "registration_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("status", models.CharField(default="active", max_length=50)),
            ],
            options={
                "ordering": ["-registration_date"],
                "indexes": [
                    models.Index(
                        fields=["-registration_date"],
                        name="mangrove_me_registr_1093b9_idx",
                    )
                ],
            },
        ),
    ]
